version: "2"

services:
  www:
    image: rogerscuall/docker_presentation1:v0.1
    ports:
      - 8000:5000
    user: nobody
    environment:
      DEBUG: 1
    command: python counter.py
    volumes:
      - ./www:/src

  redis:
    image: redis
